version: '2'
services:
    db: 
        image: mysql:8.0.29
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3306:3306"
    redis:
          image: redis
          restart: always
          ports: 
            - "6379:6379"
    es:
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
          restart: always
          ports:
            - "9200:9200"
            - "9300:9300"
    rabbitmq:
          image: rabbitmq:3
          restart: always
          ports:
            - "5672:5672"
            - "15672:15672"
    app: 
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        entrypoint: ["./migrate.sh"]
        volumes: 
            - ".:/chat-app"
        ports: 
            - "3000:3000"
        depends_on:
            - db
            - redis
            - es
            - rabbitmq
        links:
            - db
            - redis
            - es
            - rabbitmq
        environment:
            REDIS_DB: 0
            REDIS_URL: redis://127.0.0.1
            REDIS_PORT: 6379
            MYSQL_USER: root
            MYSQL_PASSWORD: admin
            MYSQL_HOST: db
            MQ_HOST: rabbitmq
            APPS_MQ_NAME: apps
            CHATS_MQ_NAME: chats
            MESSAGES_MQ_NAME: messages
            ES_HOST: es